### ISSUE TITLE
typos in IFG-leitfaden

### ISSUE THREAD

**Issue by derhuerst** [okfde/IFG-Karte#1]
There are quite a lot of typos in the [IFG leitfaden](https://github.com/arnese/IFG-Karte/blob/master/fds-leitfaden.pdf) and I'd like to correct them. Do you have the source of the PDF?

**Comment by arnese** [comment]
Oops! ist final in einer Indesign-Datei. Ginge das?

**Comment by derhuerst** [comment]
hm, das kann ich leider nicht öffnen. wenn du mir plain text gibst, kann ich dir nen diff bauen, aber das müsstest du dann per hand anpassen.

**Comment by arnese** [comment]
Allet klar. Ist jetzt hier: https://github.com/arnese/IFG-Karte/blob/master/leitfaden-texte.md
Danke dir!

**Comment by derhuerst** [comment]
https://github.com/arnese/IFG-Karte/compare/master...derhuerst:master

There are a few `der/die` issues left, but most should be correct now.
